/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finchelabarcava;

/**
 *
 * @author Amatucci Simone 4INB 6/04/2017
 */
public class Finestra extends javax.swing.JFrame {

    private int x,y;
    public Finestra() {
        initComponents();
        this.x = this.Barca.getX();
        this.y = this.Barca.getY();
        Barca2.setVisible(false);
        this.x = this.Barca2.getX();
        this.y = this.Barca2.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avvia = new javax.swing.JButton();
        Arresta = new javax.swing.JButton();
        Mare = new javax.swing.JPanel();
        Barca = new javax.swing.JLabel();
        Barca2 = new javax.swing.JLabel();
        Su = new javax.swing.JButton();
        Sx = new javax.swing.JButton();
        Dx = new javax.swing.JButton();
        Giu = new javax.swing.JButton();
        Vel = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Avvia.setText("AVVIA");
        Avvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvviaActionPerformed(evt);
            }
        });

        Arresta.setText("ARRESTA");
        Arresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrestaActionPerformed(evt);
            }
        });

        Mare.setBackground(new java.awt.Color(153, 204, 255));

        Barca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finchelabarcava/Yatch.png"))); // NOI18N

        Barca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finchelabarcava/Yatch2.png"))); // NOI18N

        javax.swing.GroupLayout MareLayout = new javax.swing.GroupLayout(Mare);
        Mare.setLayout(MareLayout);
        MareLayout.setHorizontalGroup(
            MareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MareLayout.createSequentialGroup()
                .addGroup(MareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barca, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Barca2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MareLayout.setVerticalGroup(
            MareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MareLayout.createSequentialGroup()
                .addGap(0, 315, Short.MAX_VALUE)
                .addComponent(Barca2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Su.setText("^");
        Su.setEnabled(false);
        Su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuActionPerformed(evt);
            }
        });

        Sx.setText("<");
        Sx.setEnabled(false);
        Sx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SxActionPerformed(evt);
            }
        });

        Dx.setText(">");
        Dx.setEnabled(false);
        Dx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DxActionPerformed(evt);
            }
        });

        Giu.setText("v");
        Giu.setEnabled(false);
        Giu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiuActionPerformed(evt);
            }
        });

        Vel.setPaintLabels(true);
        Vel.setPaintTicks(true);
        Vel.setSnapToTicks(true);

        jLabel2.setText("Velocità barca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sx)
                        .addGap(18, 18, 18)
                        .addComponent(Dx))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Su)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 928, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Vel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avvia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Arresta)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Giu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Mare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Avvia)
                    .addComponent(Arresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Su)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sx)
                            .addComponent(Dx)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Vel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Giu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvviaActionPerformed
     Su.setEnabled(true); 
     Sx.setEnabled(true);
     Dx.setEnabled(true);
     Giu.setEnabled(true);       
    }//GEN-LAST:event_AvviaActionPerformed

    private void ArrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrestaActionPerformed
        Su.setEnabled(false); 
        Sx.setEnabled(false);
        Dx.setEnabled(false);
        Giu.setEnabled(false);
        Barca.setLocation(x,y);
        Barca2.setLocation(x,y);
    }//GEN-LAST:event_ArrestaActionPerformed

    private void SuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuActionPerformed
        Barca.setLocation(Barca.getX(),Barca.getY()-(Vel.getValue()/2));
        Barca2.setLocation(Barca2.getX(),Barca2.getY()-(Vel.getValue()/2));
        Barca.setVisible(false);
        Barca2.setVisible(true);
        Mare.repaint();
        this.repaint();
    }//GEN-LAST:event_SuActionPerformed

    private void GiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiuActionPerformed
       Barca.setLocation(Barca.getX(),Barca.getY()+(Vel.getValue()/2));
       Barca2.setLocation(Barca2.getX(),Barca2.getY()-(Vel.getValue()/2));
       Barca.setVisible(true);
        Barca2.setVisible(false);
        Mare.repaint();
        this.repaint();
    }//GEN-LAST:event_GiuActionPerformed

    private void DxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DxActionPerformed
        Barca.setLocation(Barca.getX()+Vel.getValue(),Barca.getY());
        Barca2.setLocation(Barca2.getX()+Vel.getValue(),Barca2.getY());
        Barca.setVisible(true);
        Barca2.setVisible(false);
        Mare.repaint();
        this.repaint();
    }//GEN-LAST:event_DxActionPerformed

    private void SxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SxActionPerformed
        Barca.setLocation(Barca.getX()-Vel.getValue(),Barca.getY());
        Barca2.setLocation(Barca2.getX()+Vel.getValue(),Barca2.getY());
        Barca.setVisible(false);
        Barca2.setVisible(true);
        Mare.repaint();
        this.repaint();
    }//GEN-LAST:event_SxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arresta;
    private javax.swing.JButton Avvia;
    private javax.swing.JLabel Barca;
    private javax.swing.JLabel Barca2;
    private javax.swing.JButton Dx;
    private javax.swing.JButton Giu;
    private javax.swing.JPanel Mare;
    private javax.swing.JButton Su;
    private javax.swing.JButton Sx;
    private javax.swing.JSlider Vel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
